please merge pls pls
GrainCult/GrainOS pull request #1
Opened 2024-03-21 13:22 UTC by delta2571

2024-03-21 14:24 UTC, m0thman70 commented
i would if i could

2024-03-21 14:26 UTC, m0thman70 approved these changes
I saw arch install scripts being added but i suppose for now that's fine just make sure to change that

2024-03-21 16:25 UTC, m0thman70 approved these changes
Looks good, i think this should be merged with main

2024-03-22 18:41 UTC, electron271 commented
do not remove xfce and add gnome until we have a consensus

2024-03-22 18:41 UTC, electron271 requested changes
see above

2024-03-22 18:42 UTC, electron271 commented
https://github.com/delta2571/GrainOS/pull/4

2024-03-22 18:48 UTC, electron271 commented on archiso/packages.x86_64
> +alacritty
suggestion: kitty

2024-03-22 22:35 UTC, merged